import { existsSync, mkdirSync, writeFileSync, copyFileSync, readdirSync } from 'node:fs';
import { join } from 'node:path';
import { getViewerDir } from '../utils/paths.js';

/**
 * Copy the viewer template to .archrip/viewer/
 */
export function installViewer(archripDir: string): void {
  const viewerSrc = getViewerDir();
  const viewerDest = join(archripDir, 'viewer');

  if (!existsSync(viewerSrc)) {
    throw new Error(
      'Viewer template not found. This is a packaging error.\n'
      + 'Please reinstall archrip: npm install -g archrip',
    );
  }

  mkdirSync(viewerDest, { recursive: true });

  // Copy viewer files recursively, skipping node_modules, dist, and package-lock.json
  // package-lock.json is excluded because it is generated by the user's `npm install`
  // and should not be overwritten by the bundled template version.
  copyDirRecursive(viewerSrc, viewerDest, ['node_modules', 'dist', '.tsbuildinfo', 'package-lock.json']);

  // Write marker file to verify viewer origin in build/serve
  writeFileSync(join(viewerDest, '.archrip-viewer'), 'archrip-official-viewer\n');
  console.log('  + .archrip/viewer/ (viewer template)');
}

function copyDirRecursive(src: string, dest: string, skipDirs: string[]): void {
  mkdirSync(dest, { recursive: true });
  const entries = readdirSync(src, { withFileTypes: true });
  for (const entry of entries) {
    if (skipDirs.includes(entry.name)) continue;
    // Skip symlinks to prevent path traversal via symlink injection
    if (entry.isSymbolicLink()) continue;
    const srcPath = join(src, entry.name);
    const destPath = join(dest, entry.name);
    if (entry.isDirectory()) {
      copyDirRecursive(srcPath, destPath, skipDirs);
    } else {
      copyFileSync(srcPath, destPath);
    }
  }
}
